name: edutrack
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  # icon
  cupertino_icons: ^1.0.0
  iconly: ^1.0.1
  zoom_tap_animation: ^1.1.0


  dio: ^5.2.1+1


  # otp
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.1  
  
  # auth
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3


  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  
  assets:
    - assets/img/

